source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'

pod 'RestKit'
pod 'MagicalRecord'
pod 'Reachability'
pod 'AFNetworking', '< 2.0'
pod 'TRVSMonitor'
pod 'UIKitCategoryAdditions'
pod 'SDWebImage'
pod 'MBProgressHUD', '~> 0.8'
pod 'GoogleAnalytics-iOS-SDK'
pod 'FlurrySDK', '< 5.1.0'
pod 'SocketRocket'
pod 'iOS-Slide-Menu'
pod 'YandexMapKit', '1.0.7'